### ISSUE TITLE
Add expvar support

### ISSUE THREAD

**Issue by alecha** [codegangsta/negroni#102]
I'd like to use the [expvar](https://golang.org/pkg/expvar) package, and like other packages the router is a 'catch-all' and the /debug/vars request returns 404.

It's possible to add support for it? (like [here](https://github.com/gin-gonic/gin/issues/203) )

Thanks.

**Comment by meatballhat** [comment]
@alecha Hey, sorry for the delay.  I can't speak for the reasoning behind the way the gin team implemented this via a copy of the stdlib implementation, but I know that "re-adding" the `/debug/vars` route can be done by routing to the `http.DefaultServeMux` like so:

``` go
mux := NewFancyMuxer()
// assuming a FancyMuxer has a method `Handle` that accepts a route string and `http.Handler`:
mux.Handle("/debug/vars", http.DefaultServeMux)
```

Will this work for you?  (I'm assuming you've solved your problem a while back, but for the sake of future generations...)

**Comment by alecha** [comment]
Don't worry, I've solved it manually following the link I've posted :)

**Comment by jszwedko** [comment]
:+1: what @meatballhat posted'll work for `negroni` too (not sure if you implied that you are using `gin` now or if you mimic'd the behavior).

Closing, but please feel free to reopen if you have any more thoughts!
