### ISSUE TITLE
Static ServeHTTP doesn't follow symlinks

### ISSUE THREAD

**Issue by steveeJ** [codegangsta/negroni#104]
Instead of following symlinks requests requests return 404. Is this intentional?

**Comment by meatballhat** [comment]
@steveeJ Hey, sorry for delay.  I'm unable to reproduce this behavior with a trivial example.  Are you able to provide some example code?

**Comment by steveeJ** [comment]
I haven't been able since. I'm pretty sure it was a mistake on my side, happy to close this. Thanks for getting to it eventually though!
