### ISSUE TITLE
Server doesn't respond for some db items

### ISSUE THREAD

**Issue by abhishekchoudhary** [codegangsta/negroni#111]
`[negroni] Completed 0  in 89.205858ms`

Notice the 0, where the HTTP code should be.

This happens when I try to read and encode some specific objects from the database, about which I see nothing special from an initial glance.

**Comment by meatballhat** [comment]
@abhishekchoudhary For the sake of clarity: negroni knows nothing about, and does not try to do anything with databases or data stores or backend services, etc..  That being said, are you able to provide some example code?

**Comment by meatballhat** [comment]
@abhishekchoudhary I'm going to close this out for now, but please yell if you'd like it reopened 😃
