### ISSUE TITLE
Problem with setting default `ResponseWriter` status to http.StatusOK

### ISSUE THREAD

**Issue by tdzienniak** [codegangsta/negroni#124]
I think there is a problem with this commit 34a385a. When status is set to something different than 0, `Before` functions are not called on response writer `Write`. Test don't show this, because there is explicit invocation of `WriteHeader`: [response_writer_test.go#L99](https://github.com/codegangsta/negroni/blob/master/response_writer_test.go#L99), but you usually not call it, you do just `Write`. This breaks some existing middlewares like [negroni-sessions](https://github.com/GoIncremental/negroni-sessions).

**Comment by jszwedko** [comment]
Thanks for the report @tdzienniak -- looking now.

**Comment by jszwedko** [comment]
Definitely a bug, see #126 for PR discussion.

**Comment by jszwedko** [comment]
Fixed by #126
