### ISSUE TITLE
Negroni does not share context accros diff middlewares properly

### ISSUE THREAD

**Issue by albertoleal** [codegangsta/negroni#59]
I'm not sure if I'm missing something, but I'm not able to use context to pass context through my middlewares:

Server:
```go
func NewApiServer() (*ApiServer, error) {
	a := &ApiServer{}
	a.n = negroni.New(negroni.NewRecovery(), negroni.HandlerFunc(errorHandlerMiddleware))
	a.drawRoutes()
	return a, nil
}

func (a *ApiServer) drawRoutes() {
	a.mux = mux.NewRouter()
	a.muxAuth = mux.NewRouter()

	a.mux.HandleFunc("/debug/helloworld", HelloWorldHandler)
	a.muxAuth.Handle("/services", &ServiceHandler{}).Methods("POST")
	a.mux.PathPrefix("/").Handler(negroni.New(negroni.HandlerFunc(authorizationMiddleware), negroni.Wrap(a.muxAuth)))
	a.n.UseHandler(a.mux)
}
```
Middlewares:
```go
func authorizationMiddleware(w http.ResponseWriter, r *http.Request, next http.HandlerFunc) {
	context.Set(r, "key", "unauthorizedRequest")
	val := context.Get(r, "key")
	log.Print(val.(string)) // It works here!
	return
}

func errorHandlerMiddleware(w http.ResponseWriter, r *http.Request, next http.HandlerFunc) {
	next(w, r)

	val := context.GetAll(r)
	log.Print(len(val)) // 0!
}
```

Just did another couple of tests:

Still "0" elements:
```go
func errorHandlerMiddleware(w http.ResponseWriter, r *http.Request, next http.HandlerFunc) {
	context.Set(r, "key", "unauthorizedRequest")
	next(w, r)

	val := context.GetAll(r)
	log.Print(len(val))
}
```

"1" element in the slice:
```go
func errorHandlerMiddleware(w http.ResponseWriter, r *http.Request, next http.HandlerFunc) {
	next(w, r)
	context.Set(r, "key", "unauthorizedRequest")
	val := context.GetAll(r)
	log.Print(len(val))
}
```

It seems that the request is being somehow "recreated" (?)

The error happens because of this line:
```go
a.mux.PathPrefix("/").Handler(negroni.New(negroni.HandlerFunc(authorizationMiddleware), negroni.Wrap(a.muxAuth)))
```

If I use the middleware like this:
```go
	a.n = negroni.New(negroni.NewRecovery(),
		negroni.HandlerFunc(errorHandlerMiddleware),
		negroni.HandlerFunc(authorizationMiddleware))
```
then it works. But I need to use the authorization middleware just for some routes :(

**Comment by sandeepraju** [comment]
@albertoleal I just came across the exact same issue. Any work arounds?

**Comment by brocaar** [comment]
This is not a negroni issue, but the default configuration of ``mux.Router``. By default ``mux`` will clear the context after it called the handler (https://github.com/gorilla/mux/blob/master/mux.go#L97). You can override this behaviour with:

```
r := mux.NewRouter()
r. KeepContext = true
```

Make sure to clear the context yourself. See also:
http://www.gorillatoolkit.org/pkg/context

*"The Routers from the packages gorilla/mux and gorilla/pat call Clear() so if you are using either of them you don't need to clear the context manually."*

**Comment by meatballhat** [comment]
I'm closing this out as it seems to have been answered adequately in comments, but please yell if you think a bug is still lurking.
