### ISSUE TITLE
Adding HandleFunc()-style interface

### ISSUE THREAD

**Issue by jeffomatic** [codegangsta/negroni#67]
This runs perilously close to an aesthetic debate, but I notice that the following does not work:

```
n := negroni.New()
f := func(w http.ResponseWriter, r *http.Request, next http.HandlerFunc) {
  ...
}
n.Use(f)
```

Whereas adding a typecast works:

```
n.Use(negroni.HandlerFunc(f))
```

This is because negroni's `Use()` takes a `negroni.Handler`, an interface satisfied by `negroni.HandlerFunc`, which is in turn equivalent to a function with `f()`'s signature. Golang doesn't try to resolve the equivalence automatically, which makes the explicit cast necessary.

There's a similar pattern in other HTTP handling libraries, including `net/http` and `gorilla/mux`, but those libraries offer `xyz.HandleFunc()` methods when you want to use plain old functions. I have no data to back this, but it feels like most straight-ahead code would use plain functions as middleware, as opposed to objects that define a middleware-style `ServeHTTP()`.

Would folks in the negroni community be opposed to adding a `HandleFunc()`-style interface, to obviate the need for the cast? I can make the pull request if there's interest, but it seems like it would be about as complicated as the following:

```
func (n *Negroni) UseFunc(handlerFunc HandlerFunc) {
	n.Use(handlerFunc)
}
```

This makes the `Negroni` interface less orthogonal, but it would reduce verbosity in what I (somewhat blindly) suspect is the majority use-case.

**Comment by pjebs** [comment]
I like the idea.
