### ISSUE TITLE
UseHandler(nil) behavior inconsistent with stdlib

### ISSUE THREAD

**Issue by nathany** [codegangsta/negroni#69]
In the standard library, passing nil to ListenAndServe makes use of DefaultServeMux():

```go
http.ListenAndServe(addr, nil)
```

Negroni UseHandler doesn't work this way:

```go
n.UseHandler(nil)
```

```
[negroni] PANIC: runtime error: invalid memory address or nil pointer dereference
```

I didn't notice this was the problem right away because I had my own little convenience function much like Run that happened to be receiving a nil mux.

Anyway, not sure if this is something that needs to be fixed or documented. Just thought I'd point out the issue I ran into when first adopting Negroni. Thanks Jeremy.

**Comment by nathany** [comment]
Maybe even just a better error from UseHandler instead of panicking down the line?

**Comment by codegangsta** [comment]
@nathany this is a good point, I will leave this issue to remind me to update the documentation

**Comment by jszwedko** [comment]
I think maybe just `panic()`ing right away with a message indicating a `nil` handler is the best approach here. The alternative is to just exit the method early (skipping the pushing of a handler onto the stack), but I think that behavior is less expected by the user (e.g. they might think that they are passing in a non-nil handler that is being ignored).

**Comment by jszwedko** [comment]
To add a bit more context, I think `negroni.Use` is fundamentally different than `http.ListenAndServe`. The latter is a convenience function that is called to start a webserver (with the `DefaultServerMux` if no handler is specified), whereas `negori.Use`s sole purpose is to push a handler onto the stack -- i.e. you wouldn't call it if you weren't trying to push a handler onto the stack -- so pushing a `nil` should be unexpected.

**Comment by jszwedko** [comment]
Did not mean to close :smile:

**Comment by nathany** [comment]
@jszwedko I agree, I think it just needs a better error message.

**Comment by nathany** [comment]
Thanks
