### ISSUE TITLE
[Question] Why does the Run func create its own logger?

### ISSUE THREAD

**Issue by lonnblad** [codegangsta/negroni#72]
Hi

Noticed that the Run function creates it's own logger instead of using the potential attached logger when creating the negroni instance.

```
func (n *Negroni) Run(addr string) {
	l := log.New(os.Stdout, "[negroni] ", 0)
	l.Printf("listening on %s", addr)
	l.Fatal(http.ListenAndServe(addr, n))
}
```

Any reason for this?

BR
Fredrik

**Comment by codegangsta** [comment]
It could technically use the attached logger. Doing so might make for a more complex solution with not a whole lot of benefit. Run is just a convenience function and all we want to know is what host:port Negroni is running on.

Closing this out. Hope I answered your question :)
