### ISSUE TITLE
Running spdy with negroni results in no spdy support.

### ISSUE THREAD

**Issue by ssoroka** [codegangsta/negroni#73]
Running spdy with negroni results in no spdy support.

Example code:

```Go
import (
  "github.com/codegangsta/negroni"
  "github.com/SlyMarbo/spdy"
  "net/http"
  "fmt"
)

mux := http.NewServeMux()
mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
    fmt.Fprintf(w, "%f", spdy.SPDYversion(w))
})
n := negroni.New()
n.UseHandler(mux)

err := spdy.ListenAndServeTLS(":443", "cert.pem", "key.pem", n)
```

See also https://github.com/SlyMarbo/spdy/issues/80

**Comment by codegangsta** [comment]
Thanks for linking this. If fixing this means exporting the ResponseWriter then we can look into supporting this

**Comment by pjebs** [comment]
+1

**Comment by meatballhat** [comment]
I'm closing this out since (afaict) `ResponseWriter` [is now public](https://godoc.org/github.com/codegangsta/negroni#ResponseWriter).  Please yell if this needs to be reopened! 😻
