### ISSUE TITLE
could i get a router param in middleware

### ISSUE THREAD

**Issue by williambao** [codegangsta/negroni#74]
Hi,
i want to check some auth in middleware, should check url param is valid. but i use mux.Vars["dbId"], it return empty. like below code,

```
// my app url
router1 := mux.NewRouter()
router1.HandleFunc("/hrm/{dbId}/users", handler)
mainRouter.PathPrefix("/hrm").Handler(negroni.New(
	middleware2,
	negroni.Wrap(router1),
))

// in middleare
func (m *middleware2) ServeHTTP(w http.ResponseWriter, req *http.Request, next http.HandlerFunc) {
    vars := mux.Vars(req)

   // the dbId is empty, how to i get router param there?
    dbId := vars["dbId"]
}
```

how can i get router param in middleware? 
thanks.

**Comment by codegangsta** [comment]
At that point, the router has not even matched the route. You will have to have the middleware execute after the route has been matched but before your handler executes

**Comment by codegangsta** [comment]
Closing, Hope this answered your question

**Comment by fiatjaf** [comment]
> You will have to have the middleware execute after the route has been matched but before your handler executes

How do you do that?

**Comment by jszwedko** [comment]
@fiatjaf something like this:

```go
// my app url
router1 := mux.NewRouter()
router1.HandleFunc("/hrm/{dbId}/users", negroni.New(
    middleware2,
    negroni.Wrap(router1),
))
```
