### ISSUE TITLE
How do I convert a handler without rewriting it?

### ISSUE THREAD

**Issue by mdfcorp** [codegangsta/negroni#78]
I have the following code, which is a handler who shows a Hello World in russian...

```go
func home(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "привет, мир!")
}
```

... And now, I want to chain a few middlewares on top of it using [gorilla/pat](https://github.com/gorilla/pat), before it gets executed, like this:

```go
router := pat.New()
router.Handle("/", negroni.New(middleware1, middleware2, home)).Methods("GET")
```
And I have several handlers with the same signature `(w http.ResponseWriter, r *http.Request)`. How can I convert them to be usable with Negroni without editing all of them?

**Comment by cnjack** [comment]
Not use the router under the negroni, but use the negroni under the router ?

**Comment by codegangsta** [comment]
You can use negroni.Wrap to wrap an http handler as a negroni handler

```
negroni.New(negroni.Wrap(foo), negroni.Wrap(bar))
```

**Comment by mdfcorp** [comment]
I've already tried doing that ([you can see the code here](http://play.golang.org/p/wY1TFt5kt9)), with no luck. I get:

```
./main.go:14: cannot use home (type func(http.ResponseWriter, *http.Request)) as type http.Handler in argument to negroni.Wrap:
	func(http.ResponseWriter, *http.Request) does not implement http.Handler (missing ServeHTTP method)
```

**Comment by codegangsta** [comment]
It looks like your funcs match the signature of http.HandlerFunc, but you
need to let the compiler know that it is a http.HandlerFunc

  var h HandlerFunc = home
  negroni.New(negroni.Wrap(h))

Or if you pull down the latest version of negroni, you can use the new func
variants.

  n := negroni.New()
  n.UseHandlerFunc(home)

**Comment by meatballhat** [comment]
@mdfcorp I'm closing this out in the hope that you've already found a solution, but please yell if the issue should be reopened 😻
