### ISSUE TITLE
About Route Specific Middleware

### ISSUE THREAD

**Issue by panjunjie** [codegangsta/negroni#79]
//front web
    router := mux.NewRouter()
    router.HandleFunc("/", controller.Index)

    //backend
    adminRoutes := mux.NewRouter()
    adminRoutes.HandleFunc("/admin/index", admin.Index)
    adminRoutes.HandleFunc("/admin/article", admin.Article)

    router.Handle("/admin", negroni.New(
      negroni.NewLogger(),
      negroni.NewStatic(http.Dir(".")),
      negroni.NewRecovery(),
      negroni.Wrap(adminRoutes),
    ))

    n.UseHandler(router)

Why the backend (eg: http://localhost:3000/admin/index , http://localhost:3000/admin/article) appeared in 404, but the front web (eg: http://localhost:3000/) is correct.

**Comment by juliancooper** [comment]
Did you figure this out?

**Comment by panjunjie** [comment]
@juliancooper: not yet. please,do you have any suggestions?

**Comment by panjunjie** [comment]
For the time being used so：

router.PathPrefix("/admin").Handler(negroni.New(
		negroni.NewLogger(),
		negroni.NewStatic(http.Dir(".")),
		negroni.NewRecovery(),
		middleware.NewCheckLogin(),
		negroni.Wrap(adminRoutes),
	))

**Comment by msanterre** [comment]
Took me a while to figure this out, but the syntax changed.

```go
func main() {
	router := mux.NewRouter()
	apiRouter := ApiRouter()

	n := negroni.Classic()
	router.HandleFunc("/", HomeHandler)

	router.PathPrefix("/api").Handler(negroni.New(
		negroni.HandlerFunc(ValidateMessage),
		negroni.Wrap(apiRouter),
	))

	n.UseHandler(router)

	n.Run(":9999")
}
```

```go
func ApiRouter() *mux.Router {
	router := mux.NewRouter()
	router.HandleFunc("/api/v1/identify", IdentifyHandler)
	return router
}
```

**Comment by panjunjie** [comment]
现在发现之前自己用错了mux，现在这么用，就好了：
//front web
router := mux.NewRouter()
router.HandleFunc("/", controller.Index)

//backend
adminRoutes := mux.NewRouter()
adminRoutes.HandleFunc("/admin/index", admin.Index)
adminRoutes.HandleFunc("/admin/article", admin.Article)

router.Handle("/admin/{[a-z]+}", negroni.New(
  negroni.NewLogger(),
  negroni.NewStatic(http.Dir(".")),
  negroni.NewRecovery(),
  negroni.Wrap(adminRoutes),
))

n.UseHandler(router)

注：router.Handle("/admin/{[a-z]+}",..)  这是一个关键的语句。

**Comment by Kinghack** [comment]
Thanks. @msanterre It helps a lot.

**Comment by Kinghack** [comment]
Hi, After did as you commented, I found that when I visit '/api/', It will still go in router(HomeHandler)first. And then go in to the ValidateMessage. I'm new to go. Is there  any easy way to give unique middleware to specific route? Thanks.

**Comment by meatballhat** [comment]
@Kinghack Sorry for the long delay.  Did you figure out a reasonable solution?

**Comment by Kinghack** [comment]
@meatballhat Yes. Problem solved. Thanks.

**Comment by jszwedko** [comment]
Thanks @Kinghack!
