### ISSUE TITLE
Disable stack trace 

### ISSUE THREAD

**Issue by pjebs** [codegangsta/negroni#89]
Is there any way to disable stack trace when app is in production after a crash?

I feel it is a security concern.

**Comment by panjunjie** [comment]
negroni 本身默认自带三个基本的中间件，他们分别是：
negroni.Recovery - Panic Recovery Middleware.
negroni.Logging - Request/Response Logging Middleware.
negroni.Static - Static File serving under the "public" directory.

如果正式环境你使用了 negroni  自带的 negroni.Logging，可以屏幕掉它，比如：
n := negroni.New(
	//negroni.NewLogger(),//注释掉自带的logger中间件
	negroni.NewStatic(http.Dir(".")),
	negroni.NewRecovery(),
)

n.Use(gzip.Gzip(gzip.DefaultCompression))
n.UseHandler(router)

**Comment by pjebs** [comment]
I need the panic recovery middlerware. I just need it to **NOT** display the stack trace when it is displayed.

**Comment by mkyung** [comment]
First you can't use `negroni.Classic()` because it uses the original recovery middleware.

Then you need to:

```go
n := negroni.New()  
recovery := negroni.NewRecovery()  
recovery.PrintStack = false  
... 
n.Use(recovery, logger, static...etc)
```

**Comment by pjebs** [comment]
thank you.
