### ISSUE TITLE
Cut a new release

### ISSUE THREAD

**Issue by dimroc** [codegangsta/negroni#93]
It's been over a year since v0.1:
https://github.com/codegangsta/negroni/releases

This helps with vendoring and dependency management.

**Comment by meatballhat** [comment]
🔜

**Comment by jszwedko** [comment]
v0.2 has been released! See https://github.com/codegangsta/negroni/blob/12bc39c6547cce972e19913c256fa6f314c901b1/CHANGELOG.md for changes.
