### ISSUE TITLE
question:Is the project  still keep developing?

### ISSUE THREAD

**Issue by panjunjie** [codegangsta/negroni#95]
question:Is the project  still keep developing?

**Comment by ryanzec** [comment]
I am also interested in this

**Comment by pjebs** [comment]
Not much happening because it is now stable.

**Comment by tsingson** [comment]
Yes，lt stable for production now.
Maybe need support http2 only

**Comment by meatballhat** [comment]
Yep!

**Comment by pjebs** [comment]
I heard a rumour that the author is suffering from depression. We should relax a bit about whether this project is still ongoing and wait for his recovery.

**Comment by meatballhat** [comment]
@pjebs I can neither confirm nor deny @codegangsta's mental state.  When we last communicated (yesterday), we exchanged parenting congrats and project management opinions.  There were exclamation points involved.  Either way: maintenance here is typical of open source, afaict.  It comes in bursts.  Hi! :wave: :smiley_cat:

**Comment by panjunjie** [comment]
@meatballhat :+1:  I really like this project, it's a good news,good job! guy.
